version: '3'

services:
  db:
    image: mysql:5.7
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: pass
  app:
    build: .
    image: registry.cubesystems.lv/cube/rimi:latest
    command: php-fpm7.1 -F
    expose:
      - 9000
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      APP_NAME: Laravel
      APP_ENV: local
      APP_KEY: base64:PO9+5rh11l8k3mY91IsRzRg+M4IxT10JFSntuEhQZZM=
      APP_DEBUG: 'true'
      APP_LOG_LEVEL: debug
      APP_URL: http://localhost
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: app
      DB_USERNAME: root
      DB_PASSWORD: pass
  nginx:
    image: nginx:latest
    ports:
      - 8081:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/application/public:cached
    depends_on:
      - app

volumes:
  mysql:
